ALTER TABLE pedidos
MODIFY COLUMN status_de_entrega ENUM(
    'AGUARDANDO_PAGAMENTO',
    'PAGAMENTO_REJEITADO',
    'PAGAMENTO_COM_SUCESSO',
    'AGUARDANDO_RETIRADA',
    'EM_TRANSITO',
    'ENTREGUE'
) NOT NULL;
